"""Train YOLOv8n from scratch (random init, no COCO pretraining) on the PPE dataset, to compare against a fine-tuned yolov8n.pt run."""

from pathlib import Path

import yaml
from ultralytics import YOLO

# --- Settings — edit these directly instead of passing CLI flags ---
# Anchored to the repo root (one level up from this file) so it works whether you run
# this from the repo root or from inside streamlit_app_joanna/.
_REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = _REPO_ROOT / "data" / "css-data"
DATA_YAML = DATA_DIR / "data.yaml"  # generated by ensure_data_yaml() below if missing
EPOCHS = 100
BATCH_SIZE = 32
IMG_SIZE = 640
PROJECT = str(_REPO_ROOT / "runs" / "scratch")  # where Ultralytics writes run outputs
RUN_NAME = "yolov8n_scratch"
# ---------------------------------------------------------------------

# Same 10 classes and order as YOLO8.ipynb's data.yaml cell — keep in sync with
# YOLO_CLASS_NAMES in train_baseline_classifier.py.
CLASS_NAMES = [
    "Hardhat", "Mask", "NO-Hardhat", "NO-Mask", "NO-Safety Vest",
    "Person", "Safety Cone", "Safety Vest", "machinery", "vehicle",
]


def ensure_data_yaml():
    """Write DATA_YAML from DATA_DIR's train/valid/test splits, if it doesn't exist yet —
    don't assume someone already ran the notebook cell that does this."""
    if DATA_YAML.exists():
        return

    for split in ("train", "valid", "test"):
        if not (DATA_DIR / split / "images").exists():
            raise SystemExit(
                f"{DATA_DIR} doesn't look like the dataset root — expected "
                f"{split}/images inside it. Download and unzip the dataset there "
                "first (see YOLO8.ipynb, Section 2, for where it comes from)."
            )

    data_cfg = {
        "train": str((DATA_DIR / "train" / "images").resolve()),
        "val": str((DATA_DIR / "valid" / "images").resolve()),
        "test": str((DATA_DIR / "test" / "images").resolve()),
        "nc": len(CLASS_NAMES),
        "names": CLASS_NAMES,
    }
    with open(DATA_YAML, "w") as f:
        yaml.safe_dump(data_cfg, f)
    print(f"Wrote {DATA_YAML}")


def main():
    ensure_data_yaml()

    # .yaml, not .pt: architecture only, nothing pretrained.
    model = YOLO("yolov8n.yaml")

    model.train(
        data=str(DATA_YAML),
        epochs=EPOCHS,
        batch=BATCH_SIZE,
        imgsz=IMG_SIZE,
        pretrained=False,  # required — Ultralytics still auto-attaches COCO weights otherwise
        project=PROJECT,
        name=RUN_NAME,
        seed=42,
    )

    metrics = model.val()
    print(f"mAP50-95: {metrics.box.map:.4f}")
    print(f"mAP50:    {metrics.box.map50:.4f}")
    print(f"Weights saved under {PROJECT}/{RUN_NAME}/weights/best.pt")
    # Expect this well below a fine-tuned yolov8n.pt run — that gap is the point.


if __name__ == "__main__":
    main()
